"""Record AI execution status and usage

Revision ID: 27279b36886e
Revises: ae8884b91f73
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '27279b36886e'
down_revision: Union[str, None] = 'ae8884b91f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_status', sa.String(length=20), nullable=False, server_default='disabled'))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_input_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_output_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_estimated_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('ai_estimated_cost')
        batch_op.drop_column('ai_output_tokens')
        batch_op.drop_column('ai_input_tokens')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_status')

    # ### end Alembic commands ###
