"""GitHub App installations deliveries and checks

Revision ID: 9699f9596c86
Revises: cf0ea9d9be85
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "9699f9596c86"
down_revision: Union[str, None] = "cf0ea9d9be85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("publish_checks", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_installation_id"),
    )
    with op.batch_alter_table("github_installations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_github_installations_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "github_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("check_run_id", sa.BigInteger(), nullable=True),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "head_sha", name="uq_check_repo_sha"),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("delivery_id", sa.String(length=100), nullable=False),
        sa.Column("dedup_key", sa.String(length=64), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("delivery_id"),
        sa.UniqueConstraint("dedup_key"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expected_head_sha", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_column("expected_head_sha")

    op.drop_table("webhook_deliveries")
    op.drop_table("github_checks")
    with op.batch_alter_table("github_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_github_installations_organization_id"))

    op.drop_table("github_installations")
    # ### end Alembic commands ###
