"""Track durable queue dispatch attempts

Revision ID: cf0ea9d9be85
Revises: 27279b36886e
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf0ea9d9be85'
down_revision: Union[str, None] = '27279b36886e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('dispatch_attempts', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('dispatch_attempts')
        batch_op.drop_column('queued_at')

    # ### end Alembic commands ###
